"""Project-specific metadata for the local runtime."""

from agents.models import ProjectSpec

PROJECT_CONTEXT = {'repo_name': 'Synthesis-Zyfai',
 'project_name': 'YieldMind Engine',
 'track': 'Zyfai',
 'pitch': 'A yield-aware operator that measures available yield, budgets compute '
          'spend, and prepares payout plans for AI workloads.',
 'idea_titles': ['Yield-Powered AI Wallet',
                 'Subaccount Compute Treasury',
                 'Programmable Yield Router'],
 'architecture_summary': 'A yield-aware operator loop measures available yield, '
                         'budgets compute spend, and prepares payout plans for AI '
                         'workloads. The contract side captures subaccount rules, '
                         'proof hashes, and treasury checkpoints so Zyfai-specific '
                         'live flows can be added later.',
 'overlap_targets': ['Bankr Gateway',
                     'PayWithLocus',
                     'Venice Private Agents',
                     'ERC-8004 Receipts',
                     'Uniswap Agentic Finance',
                     'Lido stETH Treasury'],
 'primary_contract_name': 'YieldMindController',
 'primary_python_module': 'zyfai_engine',
 'category': 'yield',
 'daily_budget_usd': 114,
 'per_action_budget_usd': 28,
 'cooldown_seconds': 900,
 'discovery_inputs': [{'name': 'yield_state',
                       'description': 'Current yield, strategy selection, and '
                                      'reserves.'},
                      {'name': 'compute_budget',
                       'description': 'Spendable inference headroom.'},
                      {'name': 'payout_plan',
                       'description': 'Who gets paid from the available yield.'},
                      {'name': 'receipts',
                       'description': 'Proofs and verification metadata.'}],
 'live_demo_steps': ['Copy .env.example to .env and fill the required keys.',
                     'Deploy the contract with forge script script/Deploy.s.sol '
                     '--broadcast for YieldMindController.',
                     'Run python3 scripts/run_agent.py to produce a dry run for '
                     'zyfai_engine.',
                     'Set LIVE_MODE=true and rerun python3 scripts/run_agent.py with '
                     'real credentials.',
                     'Run python3 scripts/render_submission.py and attach TxIDs plus '
                     'repo links.'],
 'partners': [{'name': 'Zyfai',
               'docs_url': 'https://docs.zyf.ai/',
               'env_vars': ['ZYFAI_API_KEY', 'ZYFAI_STRATEGY_URL'],
               'endpoint_env': 'ZYFAI_STRATEGY_URL',
               'action_kind': 'rest_json',
               'purpose': 'Measure yield headroom and budget compute spend.'},
              {'name': 'Bankr Gateway',
               'docs_url': 'https://bankr.bot/',
               'env_vars': ['BANKR_API_KEY',
                            'BANKR_CHAT_COMPLETIONS_URL',
                            'BANKR_MODEL'],
               'endpoint_env': 'BANKR_CHAT_COMPLETIONS_URL',
               'action_kind': 'rest_json',
               'purpose': 'Route inference through cost-aware model selection.'},
              {'name': 'PayWithLocus',
               'docs_url': 'https://docs.locus.finance/',
               'env_vars': ['LOCUS_API_KEY', 'LOCUS_PAYMENT_URL'],
               'endpoint_env': 'LOCUS_PAYMENT_URL',
               'action_kind': 'rest_json',
               'purpose': 'Create bounded subaccounts and controlled spend flows.'},
              {'name': 'Venice',
               'docs_url': 'https://docs.venice.ai/',
               'env_vars': ['VENICE_API_KEY',
                            'VENICE_CHAT_COMPLETIONS_URL',
                            'VENICE_MODEL'],
               'endpoint_env': 'VENICE_CHAT_COMPLETIONS_URL',
               'action_kind': 'rest_json',
               'purpose': 'Run private reasoning over sensitive inputs.'},
              {'name': 'ERC-8004 Receipts',
               'docs_url': 'https://eips.ethereum.org/EIPS/eip-8004',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Anchor identity, task receipts, and reputation updates.'},
              {'name': 'Uniswap',
               'docs_url': 'https://developers.uniswap.org/',
               'env_vars': ['UNISWAP_API_KEY', 'UNISWAP_QUOTE_URL'],
               'endpoint_env': 'UNISWAP_QUOTE_URL',
               'action_kind': 'rest_json',
               'purpose': 'Quote swaps and bounded liquidity moves.'},
              {'name': 'Lido',
               'docs_url': 'https://docs.lido.fi/',
               'env_vars': ['RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Route staking yield through guarded treasury actions.'}],
 'actions': [{'id': 'zyfai_yield_budget',
              'target': 'zyfai',
              'purpose': 'Use Zyfai for a bounded action in this repo.',
              'partner': 'Zyfai',
              'action_kind': 'rest_json',
              'max_amount_usd': 60,
              'priority': 100,
              'sensitivity': 'medium',
              'notes': ['Call Zyfai only after a dry-run artifact exists.',
                        'Use https://docs.zyf.ai/ for credential setup.']},
             {'id': 'bankr_gateway_compute_route',
              'target': 'bankr_gateway',
              'purpose': 'Use Bankr Gateway for a bounded action in this repo.',
              'partner': 'Bankr Gateway',
              'action_kind': 'rest_json',
              'max_amount_usd': 10,
              'priority': 95,
              'sensitivity': 'high',
              'notes': ['Call Bankr Gateway only after a dry-run artifact exists.',
                        'Use https://bankr.bot/ for credential setup.']},
             {'id': 'paywithlocus_subaccount_pay',
              'target': 'paywithlocus',
              'purpose': 'Use PayWithLocus for a bounded action in this repo.',
              'partner': 'PayWithLocus',
              'action_kind': 'rest_json',
              'max_amount_usd': 120,
              'priority': 90,
              'sensitivity': 'medium',
              'notes': ['Call PayWithLocus only after a dry-run artifact exists.',
                        'Use https://docs.locus.finance/ for credential setup.']},
             {'id': 'venice_private_analysis',
              'target': 'venice',
              'purpose': 'Use Venice for a bounded action in this repo.',
              'partner': 'Venice',
              'action_kind': 'rest_json',
              'max_amount_usd': 5,
              'priority': 85,
              'sensitivity': 'high',
              'notes': ['Call Venice only after a dry-run artifact exists.',
                        'Use https://docs.venice.ai/ for credential setup.']},
             {'id': 'erc_8004_receipts_receipt_anchor',
              'target': 'erc_8004_receipts',
              'purpose': 'Use ERC-8004 Receipts for a bounded action in this repo.',
              'partner': 'ERC-8004 Receipts',
              'action_kind': 'contract_call',
              'max_amount_usd': 1,
              'priority': 80,
              'sensitivity': 'medium',
              'notes': ['Call ERC-8004 Receipts only after a dry-run artifact exists.',
                        'Use https://eips.ethereum.org/EIPS/eip-8004 for credential '
                        'setup.']},
             {'id': 'uniswap_quote_route',
              'target': 'uniswap',
              'purpose': 'Use Uniswap for a bounded action in this repo.',
              'partner': 'Uniswap',
              'action_kind': 'rest_json',
              'max_amount_usd': 220,
              'priority': 75,
              'sensitivity': 'medium',
              'notes': ['Call Uniswap only after a dry-run artifact exists.',
                        'Use https://developers.uniswap.org/ for credential setup.']},
             {'id': 'lido_yield_route',
              'target': 'lido',
              'purpose': 'Use Lido for a bounded action in this repo.',
              'partner': 'Lido',
              'action_kind': 'contract_call',
              'max_amount_usd': 200,
              'priority': 70,
              'sensitivity': 'medium',
              'notes': ['Call Lido only after a dry-run artifact exists.',
                        'Use https://docs.lido.fi/ for credential setup.']}]}


def build_project_spec() -> ProjectSpec:
    """Return the repository-specific project metadata."""
    return ProjectSpec.from_dict(PROJECT_CONTEXT)
